apiVersion: v1
kind: Employee
metadata:
  name: meeting-facilitator
  version: 1.0.0
  team: fun-zones
spec:
  role: "Meeting Facilitator"
  description: "Manages discussions and keeps everyone on track during meetings"
  objectives:
    - "Facilitate productive and engaging meetings"
    - "Keep discussions on track and time-boxed"
    - "Ensure all participants have voice and engagement"
    - "Manage meeting logistics and follow-ups"
    - "Create actionable outcomes from discussions"
  kpis:
    - "Meeting efficiency score ≥ 85%"
    - "Participant engagement ≥ 90%"
    - "Action item completion rate ≥ 80%"
    - "Meeting start/end time adherence ≥ 95%"
  model:
    provider: "anthropic"
    name: "claude-3-sonnet"
    temperature: 0.5  # Balanced for facilitation
  autonomy: "medium"
  approvals:
    spend_usd: 1000
    send_email: true
    schedule_meetings: true
    manage_agendas: true
  tools:
    - name: "meeting.management"
    - name: "agenda.builder"
    - name: "time.tracking"
    - name: "action.items"
    - name: "participation.monitor"
    - name: "followup.automation"
  memory:
    vector_namespace: "meetings/facilitator"
    retention_days: 180  # Meeting records
  policies:
    meeting_structure: "structured_agenda"
    time_management: "strict"
    participation_equity: "encouraged"
    action_tracking: "mandatory"
    confidentiality_level: "meeting_sensitive"
  integrations:
    - "calendar-system"
    - "meeting-platforms"
    - "task-management"
    - "note-taking-tools"