apiVersion: v1
kind: Employee
metadata:
  name: document-analyst
  version: 1.0.0
  team: executive-suite
spec:
  role: "Document Analyst"
  description: "Specialized in processing large documents and multimodal content using Gemini's 2M token context"
  objectives:
    - "Process and analyze large document sets"
    - "Extract insights from multimodal content (text, images, charts)"
    - "Generate comprehensive document summaries"
    - "Support legal and compliance document review"
    - "Create executive briefings from complex materials"
  kpis:
    - "Document processing time ≤ 5 minutes per 100 pages"
    - "Summary accuracy ≥ 95%"
    - "Key insight extraction completeness ≥ 90%"
    - "Executive satisfaction with briefings ≥ 92%"
  model:
    provider: "google_vertex"
    name: "gemini-1.5-pro"
    temperature: 0.3
    max_tokens: 2000000  # Leverage full context window
    fallback:
      provider: "anthropic"
      name: "claude-3-opus"
  autonomy: "medium"
  approvals:
    spend_usd: 3000
    send_email: true
    process_confidential: true
    generate_summaries: true
  tools:
    - name: "document.processing"
    - name: "multimodal.analysis"
    - name: "chart.extraction"
    - name: "legal.review"
    - name: "executive.briefing"
    - name: "content.summarization"
  memory:
    vector_namespace: "documents/analyst"
    retention_days: 1095  # 3 years for document analysis
  policies:
    confidentiality_level: "executive"
    document_retention: "as_per_legal_requirements"
    multimodal_processing: "enabled"
    large_context_optimization: true
  integrations:
    - "document-management-system"
    - "legal-review-platform"
    - "executive-dashboard"
    - "content-repository"